spring.application.name=careercompass-backend

# Database connection settings
spring.data.mongodb.uri=mongodb+srv://nishantk:nishant123@cluster0.jgipt2o.mongodb.net/careercompass?authSource=admin&retryWrites=true&w=majority
spring.data.mongodb.database=careercompass
spring.mongodb.uri=mongodb+srv://nishantk:nishant123@cluster0.jgipt2o.mongodb.net/careercompass?authSource=admin&retryWrites=true&w=majority
spring.mongodb.database=careercompass

# JWT Configuration
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2c9dfdf140730dff75b8be357223b24f4
jwt.expiration=86400000

# Server port
server.port=8080
